//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commandes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commandes()
        {
            this.Lignes = new HashSet<Lignes>();
        }
    
        public int Id { get; set; }
        public System.DateTime DtCreation { get; set; }
        public Nullable<System.DateTime> DtModification { get; set; }
        public Nullable<System.DateTime> DtValidation { get; set; }
        public int StatutId { get; set; }
        public int EleveId { get; set; }
        public Nullable<double> Prix { get; set; }
        public string DeletedYN { get; set; }
        public string ReferenceTransaction { get; set; }
        public string ReferenceExterne { get; set; }
        public Nullable<int> AdresseId { get; set; }
        public Nullable<int> FraiId { get; set; }
    
        public virtual Frais Frai { get; set; }
        public virtual Statuts Statut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lignes> Lignes { get; set; }
        public virtual Eleves Eleve { get; set; }
        public virtual Adresses Adresse { get; set; }
    }
}
