//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    
    public partial class ContenuResult
    {
        public Nullable<int> Id { get; set; }
        public string Titre { get; set; }
        public string DtCreation { get; set; }
        public string DtModification { get; set; }
        public string DtFin { get; set; }
        public string Texte { get; set; }
        public string Lien { get; set; }
        public string Script { get; set; }
        public string Logo { get; set; }
        public string Horizontale { get; set; }
        public string Carree { get; set; }
        public string Verticale { get; set; }
        public string Full { get; set; }
        public Nullable<int> ModeId { get; set; }
        public string ModeLibelle { get; set; }
        public string DtDebut { get; set; }
        public Nullable<bool> Exclusif { get; set; }
        public Nullable<int> EvenementId { get; set; }
        public string EvenementLibelle { get; set; }
    }
}
