//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contenus()
        {
            this.Publications = new HashSet<Publications>();
        }
    
        public int Id { get; set; }
        public string Titre { get; set; }
        public Nullable<System.DateTime> DtCreation { get; set; }
        public Nullable<System.DateTime> DtModification { get; set; }
        public Nullable<System.DateTime> DtFin { get; set; }
        public string Texte { get; set; }
        public string Lien { get; set; }
        public string Script { get; set; }
        public string Logo { get; set; }
        public string Horizontale { get; set; }
        public string Carree { get; set; }
        public string Verticale { get; set; }
        public string Full { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publications> Publications { get; set; }
    }
}
