//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    
    public partial class EleveResult
    {
        public int NbCommandes { get; set; }
        public int NbStages { get; set; }
        public int NbCours { get; set; }
        public int NbTournois { get; set; }
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Classement { get; set; }
        public string License { get; set; }
        public string Club { get; set; }
    }
}
