//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evenements()
        {
            this.Participations = new HashSet<Participations>();
            this.Publications = new HashSet<Publications>();
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DtDebut { get; set; }
        public Nullable<System.DateTime> DtFin { get; set; }
        public Nullable<System.DateTime> DtLimiteInscription { get; set; }
        public string Descriptif { get; set; }
        public Nullable<int> Maximum { get; set; }
        public string Libelle { get; set; }
        public string Photo { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<int> TypologieId { get; set; }
        public string Duree { get; set; }
        public Nullable<int> EvenementParentId { get; set; }
        public string VisibledYN { get; set; }
    
        public virtual Typologies Typologies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participations> Participations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publications> Publications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}
