//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    
    public partial class EvenementResult
    {
        public Nullable<int> Id { get; set; }
        public string Libelle { get; set; }
        public string DtDebut { get; set; }
        public string DtFin { get; set; }
        public string DtLimiteInscription { get; set; }
        public string Descriptif { get; set; }
        public Nullable<int> Maximum { get; set; }
        public string Logo { get; set; }
        public string Photo { get; set; }
        public string Bandeau { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<double> Duree { get; set; }
        public string VisibledYN { get; set; }
        public Nullable<int> EvenementParentId { get; set; }
        public string EvenementParentLibelle { get; set; }
        public string Lien { get; set; }
        public Nullable<int> TypologieId { get; set; }
        public string TypologieLibelle { get; set; }
        public Nullable<int> Minimum { get; set; }
    }
}
