//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frais
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public Nullable<double> Minimum { get; set; }
        public Nullable<double> Maximum { get; set; }
        public Nullable<double> Prix { get; set; }
    }
}
