//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lignes
    {
        public int Id { get; set; }
        public int ProduitId { get; set; }
        public int CommandeId { get; set; }
        public int Quantite { get; set; }
        public int StatutId { get; set; }
        public double Prix { get; set; }
        public Nullable<double> Reduction { get; set; }
        public string DeletedYN { get; set; }
    
        public virtual Produits Produit { get; set; }
    }
}
