//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participations
    {
        public int Id { get; set; }
        public int EvenementId { get; set; }
        public int EleveId { get; set; }
        public Nullable<double> Quantite { get; set; }
        public string DeletedYN { get; set; }
    
        public virtual Eleves Eleve { get; set; }
        public virtual Evenements Evenement { get; set; }
    }
}
