//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plannings_Stock
    {
        public int Id { get; set; }
        public Nullable<int> Creneau0809 { get; set; }
        public Nullable<int> Creneau0910 { get; set; }
        public Nullable<int> Creneau1011 { get; set; }
        public Nullable<int> Creneau1112 { get; set; }
        public Nullable<int> Creneau1213 { get; set; }
        public Nullable<int> Creneau1314 { get; set; }
        public Nullable<int> Creneau1415 { get; set; }
        public Nullable<int> Creneau1516 { get; set; }
        public Nullable<int> Creneau1617 { get; set; }
        public Nullable<int> Creneau1718 { get; set; }
        public Nullable<System.DateTime> Jour { get; set; }
    }
}
