//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    
    public partial class PlanningResult
    {
        public Nullable<int> Id { get; set; }
        public string Creneau0809 { get; set; }
        public string Creneau0910 { get; set; }
        public string Creneau1011 { get; set; }
        public string Creneau1112 { get; set; }
        public string Creneau1213 { get; set; }
        public string Creneau1314 { get; set; }
        public string Creneau1415 { get; set; }
        public string Creneau1516 { get; set; }
        public string Creneau1617 { get; set; }
        public string Creneau1718 { get; set; }
        public string Jour { get; set; }
    }
}
