//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Descriptif { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<double> Poids { get; set; }
        public Nullable<double> Hauteur { get; set; }
        public Nullable<double> Largeur { get; set; }
        public Nullable<double> Longueur { get; set; }
        public bool Depassement { get; set; }
        public Nullable<System.DateTime> DtDebut { get; set; }
        public Nullable<System.DateTime> DtFin { get; set; }
        public string Image { get; set; }
        public string Logo { get; set; }
        public string Visuel { get; set; }
        public int CategorieId { get; set; }
        public string Reference { get; set; }
    
        public virtual Categories Categorie { get; set; }
    }
}
