//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    
    public partial class ProduitResult
    {
        public Nullable<int> Id { get; set; }
        public string Reference { get; set; }
        public string Libelle { get; set; }
        public string Descriptif { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<double> Hauteur { get; set; }
        public Nullable<double> Largeur { get; set; }
        public Nullable<double> Longueur { get; set; }
        public Nullable<double> Poids { get; set; }
        public Nullable<bool> Depassement { get; set; }
        public string DtDebut { get; set; }
        public string DtFin { get; set; }
        public string Image { get; set; }
        public string Logo { get; set; }
        public string Visuel { get; set; }
        public Nullable<int> CategorieId { get; set; }
        public string CategorieLibelle { get; set; }
        public Nullable<int> NbCommandes { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
