//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Models
{
    using System;
    
    public partial class PublicationResult
    {
        public Nullable<int> Id { get; set; }
        public Nullable<int> ContenuId { get; set; }
        public Nullable<int> EmplacementId { get; set; }
    }
}
